calendar({
    "codefordc": [
        {
            "announced": true, 
            "created": 1447715153000, 
            "description": "<p>6:30 - 7:00\u00a0Participants arrive and socialize.\u00a0</p> <p>7:00 - 7:15\u00a0Group introductions and announcements from participants and organizers.</p> <p>7:15 - 9:15\u00a0Hacking! Project teams break out to work. \u00a0If you are new, join the new member orientation.</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>9:00 - 9:15 Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:15 We head out to happy hour.</p> <p>Notes:\u00a0</p> <p>\u2022 The building is wheelchair-accessible with advance notice. Please use the contact form below to let us know.</p> <p>\u2022\u00a0Text\u00a0202-791-4101\u00a0for entry if no one is at the door.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can.</p> <p>If you are new to Code for DC:\u00a0</p> <p>\u2022\u00a0Bring a laptop if you can (it\u2019s ok if you can\u2019t).</p> <p>\u2022 Take a look at\u00a0<a href=\"http://codefordc.org/projects\">our projects</a>.</p> <p>\u2022\u00a0Review the\u00a0<a href=\"http://codefordc.org/resources/codeofconduct.html\">Code for DC Code of Conduct</a>.</p> <p>\u2022 Feel free to\u00a0<a href=\"http://codefordc.org/contact.html\">contact us</a>\u00a0with any questions, concerns, etc.</p> <p>\u2022\u00a0If you had a good time, join\u00a0<a href=\"http://groups.google.com/forum/#!forum/dc-cfa-brigade\">Google Group</a>, <a href=\"https://codefordc.org/joinslack\">Slack</a>,\u00a0and Meetup to stay in the loop.</p>", 
            "duration": 9900000, 
            "event_url": "http://www.meetup.com/Code-for-DC/events/226822859/", 
            "group": {
                "created": 1375990708000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 9724492, 
                "join_mode": "open", 
                "name": "Code for DC", 
                "urlname": "Code-for-DC", 
                "who": "Civic Hackers"
            }, 
            "headcount": 0, 
            "id": "226822859", 
            "maybe_rsvp_count": 0, 
            "name": "Civic Hacknight", 
            "status": "upcoming", 
            "time": 1450740600000, 
            "updated": 1447715153000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "419 7th St NW, Third Floor", 
                "city": "Washington", 
                "country": "us", 
                "id": 23752411, 
                "lat": 0, 
                "lon": 0, 
                "name": "Impact Hub DC", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 48
        }
    ], 
    "other": [
        {
            "created": 1450148913000, 
            "description": "<p>Start the new year by learning to code! We will be going over our <a href=\"http://bit.ly/first-timers-guide\">First Timer's Guide</a> in a casual workshop setting.</p> <p>Front End Hack Night (FEHN) is a study group where women can come together and help each other learn and understand web development. We welcome devs of all levels and encourage those with more experience to help out those that are just starting. There's always at least one mentor or leader present to help you with best practices or to guide you through if you are stuck with a nasty problem!\u00a0</p> <p><b>Laptop Policy</b></p> <p>In order to maximize your benefits from FEHN, please bring your laptop. Extra computers will not be available at the event. Even if you have never coded before, you will be coding at FEHN!</p> <p><b>Agenda\u00a0</b></p> <p>\u2022 6:30pm - Setup</p> <p>\u2022 6:40 - 6:50pm - Quick introductions</p> <p>\u2022 6:50 - 8:00pm - Code!</p> <p>\u2022 8:00 - 8:15pm - Lightning Talk - a quick presentation or talk (if scheduled)</p> <p>\u2022 8:15 - 8:30pm - Wrap Up</p> <p><b>Resources</b></p> <p>To learn more about us please visit our Github page - <a href=\"http://bit.ly/frontendhacknight\" class=\"linkified\">http://bit.ly/frontendhacknight</a></p> <p>\u2022 First Timer's Guide: <a href=\"http://bit.ly/first-timers-guide\" class=\"linkified\">http://bit.ly/first-timers-guide</a>\u00a0</p> <p>\u2022\u00a0HTML Study Guide: <a href=\"http://bit.ly/html-study-guide\" class=\"linkified\">http://bit.ly/html-study-guide</a>\u00a0</p> <p>\u2022 JavaScript Study Guide: <a href=\"http://bit.ly/js-study-guide\" class=\"linkified\">http://bit.ly/js-study-guide</a>\u00a0</p> <p><b>Building Access</b></p> <p>Certain building management companies require Meetup hosts to let people in and do not encourage them being contacted. Please respect the policy. In case the location requires access to the building, contact the group lead if information is provided or drop a comment on the Meetup page. We'll come and get you.</p> <p><b>Welcome</b>\u00a0</p> <p>This event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227427765/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "rszwmlyvcbgb", 
            "maybe_rsvp_count": 0, 
            "name": "Front End Hack Night - First Timer's\u00ad Night", 
            "status": "upcoming", 
            "time": 1451950200000, 
            "updated": 1450212001000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "641 S St NW, First Floor", 
                "city": "Washington", 
                "country": "us", 
                "id": 23929782, 
                "lat": 38.914551000000003, 
                "lon": -77.021095000000003, 
                "name": "iStrategy Labs", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 33
        }, 
        {
            "created": 1449249912000, 
            "description": "<p>On the first Tuesday of January, we will be kicking off our fourth year of the DC API meetup, a joyous and vibrant occasion possibly on par with the beginning of an entire new calendar year! \u00a0:) \u00a0</p> <p>I know there's always plenty of distractions around this time of year, so go ahead and mark your calendars now. \u00a0There will be plenty to eat, drink, and talk about, plus it'll just be good to see everyone again as we settle back into the new year. \u00a0</p> <p>6:00pm - 6:45pm Food, drinks and networking\u00a0<br/>6:45pm - 6:55pm Introductions and Announcements\u00a0<br/>6:55pm - 8:00pm Presentations</p> <p>* Bob Simons -\u00a0National Oceanic and Atmospheric Administration<br/>*\u00a0Carson Evans - Digital Ambit\u00a0<br/>* TBA\u00a0</p> <p>7:55pm - 8:00pm Refill your beverage\u00a0<br/>8:00pm - 8:30pm Panel discussions\u00a0<br/>8:30pm - 9:00pm Networking</p>", 
            "event_url": "http://www.meetup.com/DC-Web-API-User-Group/events/227211377/", 
            "group": {
                "created": 1347647025000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.069999694824219, 
                "id": 4930742, 
                "join_mode": "open", 
                "name": "DC Web API User Group", 
                "urlname": "DC-Web-API-User-Group", 
                "who": "API enthusiasts"
            }, 
            "headcount": 0, 
            "id": "227211377", 
            "maybe_rsvp_count": 0, 
            "name": "DC API User Group - January Edition", 
            "status": "upcoming", 
            "time": 1452034800000, 
            "updated": 1449249912000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1800 Massachusetts Ave NW, 2nd Floor", 
                "city": "Washington", 
                "country": "us", 
                "id": 23841139, 
                "lat": 38.908771999999999, 
                "lon": -77.042266999999995, 
                "name": "CHIEF", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 39
        }, 
        {
            "created": 1447431964000, 
            "description": "<p>Interested in learning Ruby and ails with an awesome group of women? Looking to build your first web app, learn more about coding, or build on existing skills?</p> <p>Come to our\u00a0First Timer's Night\u00a0Ruby on Rails(ROR) Study Group. This event is intended for those new to programming and/or ROR (but we welcome people of all levels to attend and help out)! The agenda will include a lecture that covers Ruby and Rails and an installfest to help you set up Rails on your own computer.</p> <p>This event is intended to be exclusively open for people who identify as women - we are transgender friendly.</p> <p>Please bring a laptop to the event so you can participate in\u00a0the installfest!</p> <p>Check out our ROR guide for more info about what we will be covering on Wednesday:\u00a0<a href=\"http://bit.ly/wwcrailsguide\"><a href=\"http://bit.ly/wwcrailsguide\" class=\"linkified\">http://bit.ly/wwcrailsguide</a></a></p> <p>Getting in the Building</p> <p>The building locks its doors at 6pm, but there will be someone at the door to let you in.\u00a0 If not please comment here or on Slack (if you're signed up for it, see resource link below if not) and someone will come get you. \u00a0There should also be a sign on the door with contact information for one of the leads.</p> <p>Meetup Agenda</p> <p>\u2022\u00a06:30pm - Setup</p> <p>\u2022 6:40 - 6:50pm - Quick introductions</p> <p>\u2022 6:50 - 7:10pm - Introduction talk to Ruby and Rails\u00a0</p> <p>\u2022 7:10 - 8:10pm - Install necessary software following the\u00a0<a href=\"http://installrails.com/\">InstallRails</a>\u00a0guide.\u00a0</p> <p>\u2022 8:15 - 8:30pm - Wrap Up</p> <p>RESOURCES</p> <p>These are the resources that members have been following along, feel free to suggest if you have more to add!</p> <p><a href=\"https://github.com/womenwhocodedc/organization/blob/master/learning-resources/ruby-on-rails/rails_guide.md\"><a href=\"https://github.com/womenwhocodedc/organization/blob/master/learning-resources/ruby-on-rails/rails_guide.md\" class=\"linkified\">https://github.com/womenwhocodedc/organization/blob/master/learning-resources/ruby-on-rails/rails_guide.md</a></a></p> <p>Request to join our Slack channel for communication:</p> <p><a href=\"http://bit.ly/wwcdcslack\"><a href=\"http://bit.ly/wwcdcslack\" class=\"linkified\">http://bit.ly/wwcdcslack</a></a></p> <p>Install Guide:</p> <p><a href=\"http://installrails.com/\"><a href=\"http://installrails.com/\" class=\"linkified\">http://installrails.com/</a></a>\u00a0</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226752382/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "226752382", 
            "maybe_rsvp_count": 0, 
            "name": "Ruby on Rails: First Timer's Night!", 
            "status": "upcoming", 
            "time": 1452123000000, 
            "updated": 1447431964000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 19
        }, 
        {
            "created": 1446219481000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)</p> <p><br/>There will be food at this event!</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226455086/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "jzwvllyvcbjb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night(Beginner's Night)", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1452123000000, 
            "updated": 1446219481000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 26
        }, 
        {
            "created": 1443771281000, 
            "description": "<p><img src=\"http://photos3.meetupstatic.com/photos/event/a/0/6/2/600_445121058.jpeg\" /></p> <p>Part awards show, part new years party, all \u202a#\u200elegalhack\u202c.</p> <p><br/>On January 6th, join DC Legal Hackers for our second annual Le Hackie Awards! Le Hackie Awards is our chance to celebrate the awesome achievements of the legal hacking movement in DC. Once again, we're taking over the Loft at 600 on F Street NW (2nd floor lounge) for food, entertainment, and celebration. Learn more at:\u00a0<a href=\"https://lehackies2.splashthat.com/\" class=\"linkified\">https://lehackies2.splashthat.com/</a></p> <p><br/><b>Space is limited, be sure to RSVP for entry.</b></p>", 
            "event_url": "http://www.meetup.com/DCLegalHackers/events/225773453/", 
            "group": {
                "created": 1372871984000, 
                "group_lat": 38.919998168945312, 
                "group_lon": -77.040000915527344, 
                "id": 9201422, 
                "join_mode": "open", 
                "name": "DCLegalHackers", 
                "urlname": "DCLegalHackers", 
                "who": "Legal Hackers"
            }, 
            "headcount": 0, 
            "id": "225773453", 
            "maybe_rsvp_count": 0, 
            "name": "Le Hackies #2", 
            "rsvp_limit": 100, 
            "status": "upcoming", 
            "time": 1452124800000, 
            "updated": 1450142415000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "600 F Street NW, Washington, DC 20004", 
                "city": "Washington", 
                "country": "us", 
                "id": 24256613, 
                "lat": 38.897072000000001, 
                "lon": -77.020156999999998, 
                "name": "The Loft at 600 F", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 15
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/221052561/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvcbjb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1452124800000, 
            "updated": 1446214011000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 17
        }, 
        {
            "created": 1449702357000, 
            "description": "<p>Emma Grasmeder, our Director of Study Groups, is moving to Berlin. Join us for a Happy Hour Farewell in her honor. She will be sharing advice about how to overcome Imposter Syndrome and other words of technical and cultural wisdom. We will miss her dearly!!</p> <p><b>Evening Schedule of Events:</b></p> <p>6:00-7:00 p.m. Registration and Happy Hour</p> <p>7:00 p.m. Talk by Emma Grasmeder and Toasts, then more Happy Hour</p> <p>8:00 p.m. Finish</p> <p>Whether or not you can attend this event, please take a moment to tell Emma how much you appreciate her by signing our <a href=\"https://docs.google.com/forms/d/1ERZFQjFtSKo732Q8_EN8stCrIdPR842Bat6Q8nAkDQg/viewform\">digital guestbook</a>.\u00a0 Thank you and we hope to see you there!</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227324943/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "227324943", 
            "maybe_rsvp_count": 0, 
            "name": "Farewell to Emma Grasmeder and \"How to Punch Imposter Syndrome in the Face\"", 
            "rsvp_limit": 150, 
            "status": "upcoming", 
            "time": 1452207600000, 
            "updated": 1449877850000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 42
        }, 
        {
            "created": 1450148912000, 
            "description": "<p>Join us for our Intro to Git night where we will be going over the basics of using the most popular VCS (We'll elaborate on what that is at the event) around.\u00a0</p> <p>Front End Hack Night (FEHN) is a study group where women can come together and help each other learn and understand web development. We welcome devs of all levels and encourage those with more experience to help out those that are just starting. There's always at least one mentor or leader present to help you with best practices or to guide you through if you are stuck with a nasty problem!\u00a0</p> <p><b>Laptop Policy</b></p> <p>In order to maximize your benefits from FEHN, please bring your laptop. Extra computers will not be available at the event. Even if you have never coded before, you will be coding at FEHN!</p> <p><b>Agenda\u00a0</b></p> <p>\u2022 6:30pm - Setup</p> <p>\u2022 6:40 - 6:50pm - Quick introductions</p> <p>\u2022 6:50 - 8:00pm - Code!</p> <p>\u2022 8:00 - 8:15pm - Lightning Talk - a quick presentation or talk (if scheduled)</p> <p>\u2022 8:15 - 8:30pm - Wrap Up</p> <p><b>Resources</b></p> <p>To learn more about us please visit our Github page - <a href=\"http://bit.ly/frontendhacknight\" class=\"linkified\">http://bit.ly/frontendhacknight</a></p> <p>\u2022 First Timer's Guide: <a href=\"http://bit.ly/first-timers-guide\" class=\"linkified\">http://bit.ly/first-timers-guide</a>\u00a0</p> <p>\u2022\u00a0HTML Study Guide: <a href=\"http://bit.ly/html-study-guide\" class=\"linkified\">http://bit.ly/html-study-guide</a>\u00a0</p> <p>\u2022 JavaScript Study Guide: <a href=\"http://bit.ly/js-study-guide\" class=\"linkified\">http://bit.ly/js-study-guide</a>\u00a0</p> <p><b>Building Access</b></p> <p>Certain building management companies require Meetup hosts to let people in and do not encourage them being contacted. Please respect the policy. In case the location requires access to the building, contact the group lead if information is provided or drop a comment on the Meetup page. We'll come and get you.</p> <p><b>Welcome</b>\u00a0</p> <p>This event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227440158/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "rszwmlyvcbpb", 
            "maybe_rsvp_count": 0, 
            "name": "Front End Hack Night - Intro to Git", 
            "status": "upcoming", 
            "time": 1452555000000, 
            "updated": 1450212614000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "700 6th Street, NW, #410", 
                "city": "Washington", 
                "country": "us", 
                "id": 23283742, 
                "lat": 38.898994000000002, 
                "lon": -77.020294000000007, 
                "name": "Social Tables", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 31
        }, 
        {
            "created": 1446220149000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b>\u00a0</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226486804/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "bcxvllyvcbrb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1452727800000, 
            "updated": 1446220149000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 4
        }, 
        {
            "created": 1443565691000, 
            "description": "<p>Simply put, the goal of any good data wrangler is to make data more accessible.</p> <p>Consider the antithesis, the idea of hiding and obfuscating your data but still publishing it on the web. Let\u2019s learn from the our anti-hero, the black-hat data wrangler.</p> <p>Who wants to foil the data-wrangler?</p> <p>A corporation required to publish financial data.</p> <p>A political campaign with sensitive contributors lists.</p> <p>An industry heading toward regulation, and would like to hide their status.</p> <p>A digital content provider that displays the goods before a sale.</p> <p>A local government agency feeling the burden of being forced to respond to FOIA requests.</p> <p>In this talk Travis (organizer/Hack&amp;Tell) and Robert (organizer/Data Wranglers) will divulge the dark secrets of black-hat wrangling. You\u2019ll learn the numerous ways you can make data publicly available yet hard to obtain. In the spirit of a good hacking talk, we\u2019ll discuss all the ways to defeat each tactic.</p> <p>Join us in January! While you wait, share the worst dataset you\u2019ve ever encountered in the meetup comments.</p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225710555/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvcbjb", 
            "maybe_rsvp_count": 0, 
            "name": "Black Hat Data Wrangling", 
            "status": "upcoming", 
            "time": 1452727800000, 
            "updated": 1449660835000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "2201 G St. NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 10605112, 
                "lat": 38.898952000000001, 
                "lon": -77.048942999999994, 
                "name": "GWU, Funger Hall, Room 103", 
                "repinned": false, 
                "state": "DC", 
                "zip": "20052"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 106
        }, 
        {
            "created": 1448482603000, 
            "description": "<p><b>Note:\u00a0</b>Registration is through\u00a0<a href=\"http://www.eventbrite.com/e/speed-mix-devs-ux-and-web-managers-tickets-19708036267\">Eventbrite</a>.</p> <p>Come to the geekier &amp; UXier side of the web world. \u00a0</p> <p>Meet front and back-end developers, UX designers, user experience specialists, information architects and content strategists - along with the people who manage web projects, wrangle web systems and otherwise run websites.</p> <p>There are 2 main parts to the event:<br/>- Phase 1: Informal networking at topic tables with drinks and appetizers<br/>- Phase 2: Speed networking (where we match you with profession and interest areas)<br/>- Then more networking...</p> <p>\u00a0Registration includes appetizers and drinks.\u00a0</p> <p><b>== Important Registration Information ==</b></p> <p>\u2022\u00a0When <a href=\"http://www.eventbrite.com/e/speed-mix-devs-ux-and-web-managers-tickets-19708036267\">registering</a>, please be accurate with your registration type. It will be awkward during the speed mix part since you'll be matched based on that information. \u00a0</p> <p>\u2022\u00a0This event is set up to have a balance between 3 main professions. If you don't see yours here, watch for the next one!</p> <p>\u2022\u00a0Prices go up after December 17th.</p> <p><b>== How Does It Work? ==</b></p> <p><b><i>Mingle:\u00a0</i></b>We begin with structured networking at Topic Tables. You can self-select which table to join or just mingle by the food and drink.\u00a0\u00a0Interact:\u00a0Speed</p> <p><b><i>MIX :\u00a0</i></b>You'll meet 4-6 people, in sessions of 10 minutes each. We'll match you based on information you provide.\u00a0</p> <p><b><i>eXchange:\u00a0</i></b>More networking! Exchange information with the people you've met.\u00a0</p> <p><b>== Schedule ==</b></p> <p>5:45 - Check-In opens<br/>6:00 - Structured Networking\u00a0with drinks &amp; appetizers<br/>7:00 - Speed MIX<br/>8:30 - Networking continued\u00a0</p> <p><b>== Sponsorship ==</b></p> <p>If you want to highlight your product, skills or have a recruiting table, please reach out to\u00a0<a href=\"mailto:[masked]\">[masked]</a>\u00a0for more information. \u00a0</p> <p><b>== Other Registration Details ==</b></p> <p>\u2022\u00a0Looking to sell your product or company or recruit? Be sure you use the proper registration type. You'll be able to include a link to jobs or a product page in a follow-up message.</p> <p>\u2022\u00a0If your title doesn't let us know how techie you are - include that info!\u00a0</p> <p>\u2022\u00a0If you are a looking for a job or consulting gig, we'll have flags for your nametag.</p>", 
            "event_url": "http://www.meetup.com/webcontentmavens/events/227019754/", 
            "group": {
                "created": 1189804715000, 
                "group_lat": 38.919998168945312, 
                "group_lon": -77.040000915527344, 
                "id": 685061, 
                "join_mode": "open", 
                "name": "Web Content Mavens", 
                "urlname": "webcontentmavens", 
                "who": "People interested in CMS"
            }, 
            "headcount": 0, 
            "id": "227019754", 
            "maybe_rsvp_count": 0, 
            "name": "Speed MIX: Developers, UX & Web Managers", 
            "status": "upcoming", 
            "time": 1453244400000, 
            "updated": 1448483661000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1110 Vermont Avenue NW, Suite 500", 
                "city": "Washington", 
                "country": "us", 
                "id": 19625362, 
                "lat": 38.904330999999999, 
                "lon": -77.033278999999993, 
                "name": "OpenGov Hub", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 5
        }, 
        {
            "created": 1446220217000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b> This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226486808/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "gcxvllyvcbbc", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1453332600000, 
            "updated": 1446220217000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 6
        }, 
        {
            "created": 1450148912000, 
            "description": "<p>Join us for the first Front-end Tech Talk of the Year as Pam Vong introduced us to the basics of Full-stack Javascript.</p> <p><br/>Front End Hack Night (FEHN) is a study group where women can come together and help each other learn and understand web development. We welcome devs of all levels and encourage those with more experience to help out those that are just starting. There's always at least one mentor or leader present to help you with best practices or to guide you through if you are stuck with a nasty problem!\u00a0</p> <p><b>Laptop Policy</b></p> <p>In order to maximize your benefits from FEHN, please bring your laptop. Extra computers will not be available at the event. Even if you have never coded before, you will be coding at FEHN!</p> <p><b>Agenda\u00a0</b></p> <p>\u2022 6:30pm - Setup</p> <p>\u2022 6:40 - 6:50pm - Quick introductions</p> <p>\u2022 6:50 - 8:00pm - Code!</p> <p>\u2022 8:00 - 8:15pm - Lightning Talk - a quick presentation or talk (if scheduled)</p> <p>\u2022 8:15 - 8:30pm - Wrap Up</p> <p><b>Resources</b></p> <p>To learn more about us please visit our Github page - <a href=\"http://bit.ly/frontendhacknight\" class=\"linkified\">http://bit.ly/frontendhacknight</a></p> <p>\u2022 First Timer's Guide: <a href=\"http://bit.ly/first-timers-guide\" class=\"linkified\">http://bit.ly/first-timers-guide</a>\u00a0</p> <p>\u2022\u00a0HTML Study Guide: <a href=\"http://bit.ly/html-study-guide\" class=\"linkified\">http://bit.ly/html-study-guide</a>\u00a0</p> <p>\u2022 JavaScript Study Guide: <a href=\"http://bit.ly/js-study-guide\" class=\"linkified\">http://bit.ly/js-study-guide</a>\u00a0</p> <p><b>Building Access</b></p> <p>Certain building management companies require Meetup hosts to let people in and do not encourage them being contacted. Please respect the policy. In case the location requires access to the building, contact the group lead if information is provided or drop a comment on the Meetup page. We'll come and get you.</p> <p><b>Welcome</b>\u00a0</p> <p>This event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227440295/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "rszwmlyvcbhc", 
            "maybe_rsvp_count": 0, 
            "name": "Front End Hack Night - Intro to the Mean Stack/Isomorphic Javascript", 
            "status": "upcoming", 
            "time": 1453764600000, 
            "updated": 1450222423000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1150 17th Street NW, Ste 200", 
                "city": "Washington", 
                "country": "us", 
                "id": 23263162, 
                "lat": 38.905338, 
                "lon": -77.039008999999993, 
                "name": "Socrata Office (2nd Floor)", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 24
        }, 
        {
            "created": 1450148912000, 
            "description": "<p>Start the new year by learning to code! We will be going over our <a href=\"http://bit.ly/first-timers-guide\">First Timer's Guide</a> in a casual workshop setting.</p> <p>Front End Hack Night (FEHN) is a study group where women can come together and help each other learn and understand web development. We welcome devs of all levels and encourage those with more experience to help out those that are just starting. There's always at least one mentor or leader present to help you with best practices or to guide you through if you are stuck with a nasty problem!\u00a0</p> <p><b>Laptop Policy</b></p> <p>In order to maximize your benefits from FEHN, please bring your laptop. Extra computers will not be available at the event. Even if you have never coded before, you will be coding at FEHN!</p> <p><b>Agenda\u00a0</b></p> <p>\u2022 6:30pm - Setup</p> <p>\u2022 6:40 - 6:50pm - Quick introductions</p> <p>\u2022 6:50 - 8:00pm - Code!</p> <p>\u2022 8:00 - 8:15pm - Lightning Talk - a quick presentation or talk (if scheduled)</p> <p>\u2022 8:15 - 8:30pm - Wrap Up</p> <p><b>Resources</b></p> <p>To learn more about us please visit our Github page - <a href=\"http://bit.ly/frontendhacknight\" class=\"linkified\">http://bit.ly/frontendhacknight</a></p> <p>\u2022 First Timer's Guide: <a href=\"http://bit.ly/first-timers-guide\" class=\"linkified\">http://bit.ly/first-timers-guide</a>\u00a0</p> <p>\u2022\u00a0HTML Study Guide: <a href=\"http://bit.ly/html-study-guide\" class=\"linkified\">http://bit.ly/html-study-guide</a>\u00a0</p> <p>\u2022 JavaScript Study Guide: <a href=\"http://bit.ly/js-study-guide\" class=\"linkified\">http://bit.ly/js-study-guide</a>\u00a0</p> <p><b>Building Access</b></p> <p>Certain building management companies require Meetup hosts to let people in and do not encourage them being contacted. Please respect the policy. In case the location requires access to the building, contact the group lead if information is provided or drop a comment on the Meetup page. We'll come and get you.</p> <p><b>Welcome</b>\u00a0</p> <p>This event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227440226/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "rszwmlyvdbcb", 
            "maybe_rsvp_count": 0, 
            "name": "Front End Hack Night", 
            "status": "upcoming", 
            "time": 1454369400000, 
            "updated": 1450212504000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1150 17th Street NW, Ste 200", 
                "city": "Washington", 
                "country": "us", 
                "id": 23263162, 
                "lat": 38.905338, 
                "lon": -77.039008999999993, 
                "name": "Socrata Office (2nd Floor)", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 3
        }, 
        {
            "created": 1446219481000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)</p> <p><br/>There will be food at this event!</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226486812/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "jzwvllyvdbfb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night(Beginner's Night)", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1454542200000, 
            "updated": 1446219481000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 6
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/221052563/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvdbfb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1454544000000, 
            "updated": 1446214011000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 3
        }, 
        {
            "created": 1446220149000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b>\u00a0</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226486814/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "bcxvllyvdbnb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1455147000000, 
            "updated": 1446220149000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/222987192/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvdbfb", 
            "maybe_rsvp_count": 0, 
            "name": "February Meetup", 
            "status": "upcoming", 
            "time": 1455147000000, 
            "updated": 1449257866000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1446220217000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b> This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/226486818/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "gcxvllyvdbwb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1455751800000, 
            "updated": 1446220217000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1446219481000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)</p> <p><br/>There will be food at this event!</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227387911/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "jzwvllyvfbdb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night(Beginner's Night)", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1456961400000, 
            "updated": 1446219481000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 3
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/221052566/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvfbdb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1456963200000, 
            "updated": 1446214011000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1446220149000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b>\u00a0</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/bcxvllyvfbmb/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "bcxvllyvfbmb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1457566200000, 
            "updated": 1446220149000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934610/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvfbdb", 
            "maybe_rsvp_count": 0, 
            "name": "How to Find and Mitigate Rare Catastrophic Events", 
            "status": "upcoming", 
            "time": 1457566200000, 
            "updated": 1449257857000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 5
        }, 
        {
            "created": 1446220217000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b> This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/gcxvllyvfbvb/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "gcxvllyvfbvb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1458167400000, 
            "updated": 1446220217000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1446219481000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)</p> <p><br/>There will be food at this event!</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227387914/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "jzwvllyvgbjb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night(Beginner's Night)", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1459981800000, 
            "updated": 1446219481000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 3
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvgbjb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvgbjb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1459983600000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1446220149000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b>\u00a0</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/bcxvllyvgbrb/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "bcxvllyvgbrb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1460586600000, 
            "updated": 1446220149000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934654/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvgbjb", 
            "maybe_rsvp_count": 0, 
            "name": "April Meetup", 
            "status": "upcoming", 
            "time": 1460586600000, 
            "updated": 1449242256000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1446220217000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b> This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/gcxvllyvgbbc/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "gcxvllyvgbbc", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1461191400000, 
            "updated": 1446220217000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1446219481000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)</p> <p><br/>There will be food at this event!</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/227387916/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "jzwvllyvhbgb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night(Beginner's Night)", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1462401000000, 
            "updated": 1446219481000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 3
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvhbgb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvhbgb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1462402800000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1446220149000, 
            "description": "<p>We're a group of women who want to learn and develop our Python scripting skills. Some of us are professional developers and data scientists, others are hobbyists, and some are just beginning. The study group is intended for everyone who wishes to learn more about the Python programming language. Folks of all skill levels are welcome!</p> <p><br/>We host beginners night on the first Wednesday of every month, which caters especially for absolute beginners and people with basic familiarity.</p> <p>All other study group nights will generally cover more advanced topics and work on projects more in depth, according to everyone's interests.</p> <p>(Please bring a laptop!)\u00a0</p> <p><b>Note:</b>\u00a0</p> <p>This Women Who Code DC event is intended to be exclusively open for women; we are trans* friendly.</p>", 
            "duration": 7200000, 
            "event_url": "http://www.meetup.com/Women-Who-Code-DC/events/bcxvllyvhbpb/", 
            "group": {
                "created": 1395616294000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 13508462, 
                "join_mode": "open", 
                "name": "Women Who Code DC", 
                "urlname": "Women-Who-Code-DC", 
                "who": "Coders"
            }, 
            "headcount": 0, 
            "id": "bcxvllyvhbpb", 
            "maybe_rsvp_count": 0, 
            "name": "Python - Hack Night", 
            "rsvp_limit": 50, 
            "status": "upcoming", 
            "time": 1463005800000, 
            "updated": 1446220149000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934703/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvhbgb", 
            "maybe_rsvp_count": 0, 
            "name": "May Meetup", 
            "status": "upcoming", 
            "time": 1463005800000, 
            "updated": 1449242269000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvjbcb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvjbcb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1464822000000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934754/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvjbcb", 
            "maybe_rsvp_count": 0, 
            "name": "June Meetup", 
            "status": "upcoming", 
            "time": 1465425000000, 
            "updated": 1449242274000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvkbjb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvkbjb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1467846000000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934786/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvkbjb", 
            "maybe_rsvp_count": 0, 
            "name": "July Meetup", 
            "status": "upcoming", 
            "time": 1468449000000, 
            "updated": 1449242280000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934824/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvlbfb", 
            "maybe_rsvp_count": 0, 
            "name": "August Meetup", 
            "status": "upcoming", 
            "time": 1470263400000, 
            "updated": 1444350500000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvlbfb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvlbfb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1470265200000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934861/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvmbkb", 
            "maybe_rsvp_count": 0, 
            "name": "September Meetup", 
            "status": "upcoming", 
            "time": 1473287400000, 
            "updated": 1444350516000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvmbkb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvmbkb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1473289200000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/225934884/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvnbhb", 
            "maybe_rsvp_count": 0, 
            "name": "October Meetup", 
            "status": "upcoming", 
            "time": 1475706600000, 
            "updated": 1444350530000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvnbhb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvnbhb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1475708400000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/227244151/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvpbdb", 
            "maybe_rsvp_count": 0, 
            "name": "January Meetup", 
            "status": "upcoming", 
            "time": 1478125800000, 
            "updated": 1417881835000, 
            "utc_offset": -14400000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 2
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvpbdb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvpbdb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1478127600000, 
            "updated": 1446214010000, 
            "utc_offset": -14400000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1417881835000, 
            "description": "<p><img src=\"http://photos2.meetupstatic.com/photos/event/8/e/b/c/600_432156540.jpeg\" /></p>", 
            "duration": 9000000, 
            "event_url": "http://www.meetup.com/Data-Wranglers-DC/events/hffzclyvqbkb/", 
            "group": {
                "created": 1384378071000, 
                "group_lat": 38.909999847412109, 
                "group_lon": -77.040000915527344, 
                "id": 11094242, 
                "join_mode": "open", 
                "name": "Data Wranglers DC", 
                "urlname": "Data-Wranglers-DC", 
                "who": "Data Wranglers"
            }, 
            "headcount": 0, 
            "id": "hffzclyvqbkb", 
            "maybe_rsvp_count": 0, 
            "name": "January Meetup", 
            "status": "upcoming", 
            "time": 1481153400000, 
            "updated": 1417881835000, 
            "utc_offset": -18000000, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }, 
        {
            "created": 1326383071000, 
            "description": "<p>On the first Wednesday of the month, we'll gather to socialize, network, and hear about the work people are doing with maps, GIS, geodata, and more.</p>", 
            "event_url": "http://www.meetup.com/Geo-DC/events/dlcllcyvqbkb/", 
            "group": {
                "created": 1307975249000, 
                "group_lat": 38.939998626708984, 
                "group_lon": -77.05999755859375, 
                "id": 2013511, 
                "join_mode": "open", 
                "name": "Geo DC", 
                "urlname": "Geo-DC", 
                "who": "Members"
            }, 
            "headcount": 0, 
            "how_to_find_us": "Upstairs bar", 
            "id": "dlcllcyvqbkb", 
            "maybe_rsvp_count": 0, 
            "name": "Monthly Meetup", 
            "status": "upcoming", 
            "time": 1481155200000, 
            "updated": 1446214010000, 
            "utc_offset": -18000000, 
            "venue": {
                "address_1": "1602 U St NW", 
                "city": "Washington", 
                "country": "us", 
                "id": 24181227, 
                "lat": 38.916733000000001, 
                "lon": -77.037186000000005, 
                "name": "Local 16", 
                "repinned": false, 
                "state": "DC"
            }, 
            "visibility": "public", 
            "waitlist_count": 0, 
            "yes_rsvp_count": 1
        }
    ]
})