calendar([
    {
        "created": 1406234755000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868622/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868622", 
        "maybe_rsvp_count": 0, 
        "name": "September 2014 Civic Hacknight 1", 
        "status": "upcoming", 
        "time": 1410386400000, 
        "updated": 1406234755000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 59
    }, 
    {
        "created": 1406234785000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868692/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868692", 
        "maybe_rsvp_count": 0, 
        "name": "September 2014 Civic Hacknight 2", 
        "status": "upcoming", 
        "time": 1411509600000, 
        "updated": 1406234785000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 19
    }, 
    {
        "created": 1406234837000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868812/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868812", 
        "maybe_rsvp_count": 0, 
        "name": "October 2014 Civic Hacknight 1", 
        "status": "upcoming", 
        "time": 1412805600000, 
        "updated": 1406234837000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 11
    }, 
    {
        "created": 1406234864000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868952/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868952", 
        "maybe_rsvp_count": 0, 
        "name": "October 2014 Civic Hacknight 2", 
        "status": "upcoming", 
        "time": 1414533600000, 
        "updated": 1406234864000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 10
    }, 
    {
        "created": 1404746991000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.</p> <p>Join us in September for DC Legal Hackers' Citation Hackathon</p> <p>What's a \"legal hackathon\"?</p> <p>A legal hackathon is an\u00a0event that brings together teams of lawyers, policymakers, academics, and technologists to develop innovative, on-the-spot solutions to challenging legal issues. The hackathon will present a unique problem (here: Legal Citation) for legal hackers to solve, with topics ranging from current policy debates to the role of technology in legal practice and policymaking.\u00a0During the legal hackathon, the teams will work together on a tech- or policy-based solution to the issue presented. Although you don't have to be a coder to participate, we strongly encourage non-tech participants to work together with coders on their \"legal hacks.\"\u00a0</p> <p>What will be \"hacked\" on?</p> <p>- Improving citation parsers (such as github.com/unitedstates/citation)</p> <p>- Building applications that use the parsers (such as github.com/adelevie/downlaw)</p> <p>- Anything else! If you're generally interested in legal hacking, but not in legal citations, please attend! We're happy to facilitate collaboration between lawyers and coders.</p> <p>SCHEDULE:\u00a0</p> <p>9:30 - 10 Breakfast</p> <p>10 - 12 Hacking</p> <p>12 - 12:30 Lunch</p> <p>12:30 - 4:00 Continued Hacking</p> <p><br/><i>After: drinks, pats on backs, better citation technology</i></p> <p><br/>* * * * * * * *</p> <p>\n\n\nFollow along on twitter with the hashtag #LegalHack or at <a href=\"http://www.twitter.com/DCLegalHackers\">www.twitter.com/DCLegalHackers</a></p>", 
        "duration": 21600000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193491602/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193491602", 
        "maybe_rsvp_count": 0, 
        "name": "Legal Citation Hackathon", 
        "status": "upcoming", 
        "time": 1410616800000, 
        "updated": 1410034716000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "711 D Street Northwest #200", 
            "city": "Washington", 
            "country": "us", 
            "id": 15670162, 
            "lat": 38.894897, 
            "lon": -77.022537, 
            "name": "Fastcase, Inc", 
            "repinned": false, 
            "state": "DC", 
            "zip": "20001"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 21
    }, 
    {
        "created": 1404748848000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.\u00a0</p> <p>Join us on Tuesday, August 5, 2014 to legal hack crypto/ethereum law.</p> <p>7-7:30 Food, drinks and networking\u00a0\u00a0</p> <p>7:30-7:45 Introductions and Announcements\u00a0</p> <p>7:45 - 9:00 Presentations and Discussion</p> <p>Follow along on twitter with the hashtag #LegalHack or at www.twitter.com/DCLegalHackers</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193499412/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193499412", 
        "maybe_rsvp_count": 0, 
        "name": "#LegalHack Crypto / Ethereum Law", 
        "status": "upcoming", 
        "time": 1412204400000, 
        "updated": 1406226505000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "600 New Jersey Avenue NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 19547872, 
            "lat": 38.898173999999997, 
            "lon": -77.012237999999996, 
            "name": "Georgetown Law", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 12
    }, 
    {
        "created": 1404748918000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.\u00a0</p> <p>Join us on Tuesday, August 5, 2014 to legal hack standards organizations.</p> <p>7-7:30 Food, drinks and networking\u00a0</p> <p>7:30-7:45 Introductions and Announcements\u00a0</p> <p>7:45 - 9:00 Presentations and Discussion</p> <p>Follow along on twitter with the hashtag #LegalHack or at www.twitter.com/DCLegalHackers</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193499542/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193499542", 
        "maybe_rsvp_count": 0, 
        "name": "#LegalHack Standards Organizations", 
        "status": "upcoming", 
        "time": 1415232000000, 
        "updated": 1404749244000, 
        "utc_offset": -18000000, 
        "venue": {
            "address_1": "600 New Jersey Avenue NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 19547872, 
            "lat": 38.898173999999997, 
            "lon": -77.012237999999996, 
            "name": "Georgetown Law", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 7
    }, 
    {
        "created": 1404749084000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.\u00a0</p> <p>Join us in December for our Legal Hackie Awards and Holiday Party</p> <p>7-7:30 Food, drinks and networking holiday party addition</p> <p>7:30-8:00 Award announcements and featured project recognition\u00a0</p> <p>8:00 - 9:00 Food, drinks and networking holiday party addition</p> <p>Follow along on twitter with the hashtag #LegalHack or at www.twitter.com/DCLegalHackers</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193499902/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193499902", 
        "maybe_rsvp_count": 0, 
        "name": "Legal Hackie Awards and Holiday Party (tentatively scheduled)", 
        "status": "upcoming", 
        "time": 1417651200000, 
        "updated": 1404749084000, 
        "utc_offset": -18000000, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 1
    }, 
    {
        "created": 1409686195000, 
        "description": "<p>Hack and Tell will be at WeWork Chinatown again in September! (Hooray!) Everyone is looking forward to hearing about *your* cool hack! Presentation signups are here:</p> <p><a href=\"http://bit.ly/presentatdc\"><a href=\"http://bit.ly/presentatdc\" class=\"linkified\">http://bit.ly/presentatdc</a></a></p> <p>The format is informal, engaging, and friendly: presenters have 5 minutes to show off their hack (it goes faster than you\u2019d expect) and then the audience has 5 minutes to ask questions, make jokes, and suggest ideas and feedback. The hacks that people present are anything from how to train your dog to text you when it needs a walk to [something more serious... like 3d-printing aluminum parts]. Show us what you\u2019ve got! But remember: no startup pitches, dull work projects, no deckware!</p> <p>If you\u2019re interested in presenting, complete this short form to let us know:\u00a0<a href=\"http://bit.ly/presentatdc\"><a href=\"http://bit.ly/presentatdc\" class=\"linkified\">http://bit.ly/presentatdc</a></a></p> <p>See you at the meetup! We'll start close to seven. There may be a couple beers. It's going to be fun! :) Big thanks to WeWork for hosting us! We love WeWork! We love you! We love hacks! &lt;3</p>", 
        "event_url": "http://www.meetup.com/DC-Hack-and-Tell/events/204722772/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.019996643066406, 
            "id": 7361532, 
            "join_mode": "open", 
            "name": "DC Hack and Tell", 
            "urlname": "DC-Hack-and-Tell", 
            "who": "Hackers"
        }, 
        "headcount": 0, 
        "how_to_find_us": "by the couch!", 
        "id": "204722772", 
        "maybe_rsvp_count": 0, 
        "name": "Round 13: Triskaidekaphilia", 
        "status": "upcoming", 
        "time": 1412118000000, 
        "updated": 1409686195000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "718 7th St NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 19047832, 
            "lat": 38.899109000000003, 
            "lon": -77.022223999999994, 
            "name": "WeWork Chinatown", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 31
    }, 
    {
        "created": 1409428206000, 
        "description": "<p>For our September Meetup, we're once again going to have Lightning Talks!\u00a0Eight members of our Data Science community will each be speaking for just eight minutes each. These talks will include research, lessons learned in practice, and interesting tools, all in bite-sized packages. We guarantee a great time!</p> <p><br/>The event will be co-located with the <b>Predictive Analytics World - Government</b> conference, running the 15th through the 18th, which is why the new venue and slightly-delayed time. \u00a0You do <i>not</i> have to attend the conference to attend this Meetup event -- everyone is welcome! However, if you do want to attend the conference, we have a discount code for you. <a href=\"http://www.predictiveanalyticsworld.com/gov/2014/\">Use DATADC for 15% of registration to the\u00a0largest and only vendor-neutral analytics conference for government</a>!\u00a0</p> <p><b>Note</b>: Because of hotel catering requirements, we won't be serving empenadas as usual. There may be <i>hors d'</i><i>oeuvres</i>, or something else\u00a0-- we'll let you know soon.\u00a0</p> <p><b>Agenda:</b></p> <p>\u2022\u00a07:00pm -- Networking and Refreshments <i>TBA</i></p> <p>\u2022\u00a07:30pm -- Introduction</p> <p>\u2022\u00a07:45pm -- Presentations!</p> <p>\u2022 9:00pm -- Data Drinks (<i>TBA</i>)</p> <p><b>Speakers:</b></p> <p>\u2022\u00a0<a href=\"http://stephenbach.net/\">Stephen Bach</a>, University of Maryland, <i>Statistical Relational Models for Social Good</i></p> <p>\u2022\u00a0Kevin T. Smith, <a href=\"http://www.novetta.com/\">Novetta</a>,\u00a0<i>Security and Privacy of Big Data in a Dangerous World</i></p> <p><br/>\u2022\u00a0<a href=\"https://twitter.com/nicktabbal\">Nick Tabbal</a>,\u00a0Bulletin Intelligence,\u00a0<i>Leveraging technology and human judgement to generate daily insights from Open Source Intelligence</i></p> <p><br/>\u2022\u00a0<a href=\"https://www.linkedin.com/profile/view?id=130190052\">Margaret Ward</a>, United States Coast Guard,\u00a0<i>Creating Healthy Workforce Flow</i></p> <p>\u2022 <a href=\"https://twitter.com/castrotech\">Daniel Castro</a>, Center for Data Innovation, <i>Data is Law (and Law is Data)</i></p> <p><br/>\u2022 <a href=\"https://www.linkedin.com/profile/view?id=221277\">Marck Vaisman</a>, Data Community DC, <i>From Hierarchical to Graph Data</i></p> <p><br/><i>\u2022 more to come...!</i></p> <p><b>Sponsors:</b></p> <p>This event is sponsored by <a href=\"http://www.predictiveanalyticsworld.com/gov/2014/\">Predictive Analytics World - Government</a>,\u00a0<a href=\"http://www.cloudera.com/\">Cloudera</a>,\u00a0<a href=\"http://bit.ly/12YljkP\">Statistics.com</a>,\u00a0<a href=\"https://corporate.livingsocial.com/browsealljobs/?deep_link=/jobs/olpfYfwH\">LivingSocial</a>,\u00a0<a href=\"http://novetta.com/\">Novetta Solutions</a>,\u00a0<a href=\"http://datamininglab.com/\">Elder Research</a>, and\u00a0<a href=\"http://www.five9group.com/\">Five 9 Group</a>. Would you like to sponsor too? Please get in touch!\u00a0</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/Data-Science-DC/events/204142852/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.019996643066406, 
            "id": 2215331, 
            "join_mode": "open", 
            "name": "Data Science DC", 
            "urlname": "Data-Science-DC", 
            "who": "Data Scientists"
        }, 
        "headcount": 0, 
        "id": "204142852", 
        "maybe_rsvp_count": 0, 
        "name": "Lightning Talks! (III)", 
        "status": "upcoming", 
        "time": 1410822000000, 
        "updated": 1410222653000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "1000 H St. NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 22180872, 
            "lat": 38.913868000000001, 
            "lon": -77.026176000000007, 
            "name": "Grand Hyatt Washington, Constitution B", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 184
    }, 
    {
        "created": 1408392086000, 
        "description": "<p>For October, we'll be discussing four tech projects and their impact on local transportation issues.\u00a0Doors open at 6:00 with pizza and drinks, and the presentations start at 6:30. Please note the location might be changed, so check back here for updates.</p> <p>\u2022\u00a0Trevor Gerhardt of <a href=\"http://conveyal.com/\">Conveyal</a> will show us their <a href=\"http://mobilitylab.org/transit-tech/\">Transit Tech Initiative</a> with Arlington County, specifically the \"evaluating a commute\" portion of the program.</p> <p>\u2022\u00a0Eric Meyer will tell us about the Baltimore-based <a href=\"http://www.haystackmobile.com/\">Haystack</a> mobile app, which lets people buy and sell street-side parking spaces.</p> <p>\u2022\u00a0Chase Donnelly and\u00a0Peter Mazzeo will demo their new <a href=\"http://boontrek.com/\">Boontrek</a> app, which\u00a0creates a community marketplace for ride sharing.</p> <p><br/>\u2022\u00a0Peter Shashkin and Vitaliy Fedonkin from <a href=\"http://www.eastbanctech.com/\">EastBanc Technologies</a> will show us TransitIQ, which analyzes transit data, detecting anomalies, bus bunching, and more. EastBanc works with SmarTrip cards and\u00a0is the company behind\u00a0<a href=\"http://developer.wmata.com/\">developer.wmata.com</a>.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/201709462/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "201709462", 
        "maybe_rsvp_count": 0, 
        "name": "Cool Mobility Apps: October Edition", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1412287200000, 
        "updated": 1409930260000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 31
    }, 
    {
        "created": 1407622606000, 
        "description": "<p>For our second Bike Hack Night, we're going to look at both software and hardware projects. We've got a great lineup, with more to be added:</p> <p>\u2022\u00a0Betsy\u00a0Emmons will show her animated\u00a0<a href=\"http://mapstory.org/maps/1736/\">MapStory</a>\u00a0on the history of bike lanes in DC.</p> <p><br/>\u2022\u00a0Lia Seremetis of <a href=\"http://dcbikeparty.com/\">DC Bike Party</a>\u00a0will talk about how we GPS-tracked a big bike ride and made an animation of it.</p> <p>\u2022\u00a0Shane Farthing of WABA will demo their <a href=\"http://www.waba.org/mobile-app/\">mobile app</a>.</p> <p><br/>\u2022\u00a0<a href=\"http://www.bikearlington.com/\">BikeArlington</a> will show us their upcoming app for creating a crowd-sourced map of bike racks.</p> <p><br/>\u2022\u00a0<a href=\"http://socialbicycles.com/\">SocialBicycles</a> will talk about their model of dockless bikesharing.</p> <p>\u2022\u00a0Reg Viray from the\u00a0<a href=\"https://www.vtti.vt.edu/\">Virginia Tech Transportation Institute</a>\u00a0will talk about bicycles and the future of connected vehicles.</p> <p><br/>\u2022\u00a0Ola G\u00f6ransson from the\u00a0<a href=\"http://www.swedenabroad.com/en-GB/Embassies/Washington/\">Embassy of Sweden</a>\u00a0will show us the\u00a0<a href=\"http://www.hovding.com/\">H\u00f6vding</a>\u00a0\"invisible\" helmet.</p> <p><br/>\u2022\u00a0<a href=\"http://tedullrich.com/\">Ted\u00a0Ullrich</a> of <a href=\"http://tomorrow-lab.com/\">Tomorrow Lab</a>\u00a0in New York City will show us the <a href=\"http://waycount.com/\">WayCount</a> device, which can be used to crowdsource bike traffic count data.</p> <p>If you have a bike-related app or data visualization that's creative and local, we want to see it!</p> <p>Please note there is a chance the location will be changed; we'll announce it later.</p> <p>Read about the last Bike Hack Night:\u00a0<a href=\"http://mobilitylab.org/2014/05/28/transportation-techies-show-what-can-be-done-with-bike-data/\">Transportation Techies Show What Can Be Done With Bike Data</a>.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/200015252/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "200015252", 
        "maybe_rsvp_count": 0, 
        "name": "Bike Hack Night II", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1415314800000, 
        "updated": 1409845572000, 
        "utc_offset": -18000000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 30
    }, 
    {
        "created": 1407908606000, 
        "description": "<p>Putting out the call for new and exciting apps and data visualizations about Capital Bikeshare. Read about <a href=\"http://mobilitylab.org/2013/12/11/capital-bikeshare-hackers-pedal-their-wares-at-mobility-lab/\">CaBiHackNight I</a> and <a href=\"http://mobilitylab.org/2014/08/11/cabi-hack-night-2-brings-out-nerds-who-love-bikesharing/\">CaBiHackNight II</a> to get an idea of how it works. This is a \"show and tell,\" not a hackathon. Got a cool CaBi project? We'd love to see it!</p> <p>We'll add speakers here as folks sign up:</p> <p>\u2022\u00a0Trevor Gerhardt will show us a <a href=\"http://trevorgerhardt.com/hexacabi/\">dcjs data explorer</a> for CaBi.</p> <p>\u2022\u00a0<a href=\"http://codemonkey.io/\">Mathias Hansen</a> will show us how he visualizes an individual's trip histories with his Trip statistics app.</p> <p>\u2022 Paul DeMaio, the program manager of Arlington's Capital Bikeshare service, will share a study on CaBi\u2019s first-mile/last-mile ridership.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/200661602/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "200661602", 
        "maybe_rsvp_count": 0, 
        "name": "CaBi Hack Night III", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1417734000000, 
        "updated": 1408715147000, 
        "utc_offset": -18000000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 14
    }
])