calendar([
    {
        "created": 1406234755000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868622/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868622", 
        "maybe_rsvp_count": 0, 
        "name": "September 2014 Civic Hacknight 1", 
        "status": "upcoming", 
        "time": 1410386400000, 
        "updated": 1406234755000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 24
    }, 
    {
        "created": 1406234785000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868692/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868692", 
        "maybe_rsvp_count": 0, 
        "name": "September 2014 Civic Hacknight 2", 
        "status": "upcoming", 
        "time": 1411509600000, 
        "updated": 1406234785000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 10
    }, 
    {
        "created": 1406234837000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868812/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868812", 
        "maybe_rsvp_count": 0, 
        "name": "October 2014 Civic Hacknight 1", 
        "status": "upcoming", 
        "time": 1412805600000, 
        "updated": 1406234837000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 7
    }, 
    {
        "created": 1406234864000, 
        "description": "<p>6:00 - 6:30\u00a0Participants arrive and socialize.\u00a0</p> <p>6:30 - 6:45\u00a0Group introductions and announcements from participants and organizers.</p> <p>6:45 - 8:45\u00a0Hacking. Project teams break out to work. \u00a0New participants can join teams, circulate, or seek out the Co-Captains for orientation (Justin, Matt, or Leah).</p> <p>~7:30\u00a0Food delivered.\u00a0</p> <p>8:45 - 9:00\u00a0Everyone reconvenes and shares reactions to and progress made over the last two hours. Show and tell if time/resources allow it. Thank you and goodnight.</p> <p>9:00\u00a0Sometimes an after party (Happy Hour)</p> <p>Notes:\u00a0</p> <p>\u2022\u00a0Text Matt 202-330-1154 or Justin at 301-538-5812 if you have problems.</p> <p>\u2022\u00a0Bring cash for food and drink! Pay what you can (but remember we only have a single sponsor that covers a small amount of our expenses: servers, food, etc)</p> <p>\u2022\u00a0Bring a laptop (it\u2019s ok if you can\u2019t) and review list of active projects:\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>If you are new to Code for DC\u2026\u00a0</p> <p>\u2022\u00a0Please take a look at our website\u00a0<a href=\"http://www.codefordc.org/\"><a href=\"http://www.codefordc.org\" class=\"linkified\">http://www.codefordc.org</a></a>\u00a0</p> <p>\u2022\u00a0Next take a look at our active projects\u00a0<a href=\"http://bit.ly/codefordc\"><a href=\"http://bit.ly/codefordc\" class=\"linkified\">http://bit.ly/codefordc</a></a></p> <p>\u2022\u00a0Review the Code for DC Code of Conduct (draft)<a href=\"https://github.com/codefordc/code-of-conduct\"><a href=\"https://github.com/codefordc/code-of-conduct\" class=\"linkified\">https://github.com/codefordc/code-of-conduct</a></a></p> <p>\u2022\u00a0If you are relatively new to civic hacking check out the Code for DC Getting Started Guide\u00a0<a href=\"https://github.com/codefordc/getting-started\"><a href=\"https://github.com/codefordc/getting-started\" class=\"linkified\">https://github.com/codefordc/getting-started</a></a></p> <p>\u2022\u00a0Start working on a project with someone or bring your own project</p> <p><br/>\u2022\u00a0Introduce yourself to others</p> <p>\u2022\u00a0If you had a good time join Google Group and Meetup</p>", 
        "duration": 10800000, 
        "event_url": "http://www.meetup.com/Code-for-DC/events/196868952/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.040000915527344, 
            "id": 9724492, 
            "join_mode": "open", 
            "name": "Code for DC", 
            "urlname": "Code-for-DC", 
            "who": "Civic Hackers"
        }, 
        "headcount": 0, 
        "id": "196868952", 
        "maybe_rsvp_count": 0, 
        "name": "October 2014 Civic Hacknight 2", 
        "status": "upcoming", 
        "time": 1414533600000, 
        "updated": 1406234864000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "419 7th St NW, Second Floor", 
            "city": "Washington", 
            "country": "us", 
            "id": 20407722, 
            "lat": 0, 
            "lon": 0, 
            "name": "Impact Hub DC", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 7
    }, 
    {
        "created": 1404746039000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.</p> <p>Join us on Tuesday, September 3, 2014 to legal hack copyright and bring back CopyNight to DC!</p> <p><img src=\"http://photos4.meetupstatic.com/photos/event/1/a/c/4/600_397326852.jpeg\" /></p> <p>7-7:30 Food, drinks and networking\u00a0</p> <p><br/>7:30-7:45 Introductions and Announcements\u00a0</p> <p>7:45 - 9:00 Discussion, co-lead by:</p> <p>\u2022 <a href=\"http://alisternburg.com/about/\">Ali Sternburg</a>,\u00a0Public Policy &amp; Regulatory Counsel\u00a0at the Computer &amp; Communications Industry Association (CCIA)<a href=\"https://twitter.com/CCIAnet\">&lt;/a&gt;</p> <p><br/>\u2022 &lt;a href=\"http://tushnet.com/about/\"&gt;Rebecca Tushnet</a>, Professor of Law at Georgetown Law School, teaching\u00a0intellectual property, advertising law, and First Amendment law.</p> <p>\u2022\u00a0<a href=\"http://cei.org/expert/ryan-radia\">Ryan Radia</a>,\u00a0Associate Director of Technology Studies of Competitive Enterprise Institute\u00a0</p> <p><br/>Follow along on twitter with the hashtag #LegalHack or at <a href=\"http://www.twitter.com/DCLegalHackers\">www.twitter.com/DCLegalHackers</a></p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193489092/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193489092", 
        "maybe_rsvp_count": 0, 
        "name": "#LegalHack CopyNight", 
        "status": "upcoming", 
        "time": 1409785200000, 
        "updated": 1409168202000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "600 New Jersey Avenue, NW ", 
            "city": "Washington", 
            "country": "us", 
            "id": 19790922, 
            "lat": 38.898173999999997, 
            "lon": -77.012237999999996, 
            "name": "McDonough Hall, Room 200  Georgetown University Law Center ", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 31
    }, 
    {
        "created": 1404746991000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.</p> <p>Join us in September for DC Legal Hackers' Citation Hackathon</p> <p>What's a \"legal hackathon\"?</p> <p>A legal hackathon is an\u00a0event that brings together teams of lawyers, policymakers, academics, and technologists to develop innovative, on-the-spot solutions to challenging legal issues. The hackathon will present a unique problem (here: Access to Justice) for legal hackers to solve, with topics ranging from current policy debates to the role of technology in legal practice and policymaking.\u00a0During the legal hackathon, the teams will work together on a tech- or policy-based solution to the issue presented. Although you don't have to be a coder to participate, we strongly encourage non-tech participants to work together with coders on their \"legal hacks.\"\u00a0</p> <p>What will be \"hacked\" on?</p> <p>PRIMARY ISSUE STATEMENT:\u00a0\u00a0Improving legal citation through hyperlinks!</p> <p>SCHEDULE:\u00a0</p> <p>9:30-10 Breakfast</p> <p>10 Github 101</p> <p>10:30 Citation 101</p> <p>11 Presenting the Access to Justice problem &amp; team forming*</p> <p>11-4:00 Hacking\u00a0with lunch.</p> <p>4:00 Presentations,\u00a0discussion, and next steps.\u00a0</p> <p><i>After: drinks, pats on backs, better linked citations</i></p> <p>* * * * * * * *</p> <p>*For those inclined, we have also outlined a few alternative tracks:</p> <p>\u2022\u00a0<a href=\"http://www.dcregs.dc.gov/\">DC regulatory law</a>\u00a0data modeling.\u00a0</p> <p>\u2022\u00a0<a href=\"http://hypothes.is/blog/annotating-the-law/\">Legal Annotation</a></p> <p><br/>\u2022 Legal Services Corp mapping</p> <p><br/>\u2022 Your legal tech idea!\u00a0</p> <p>Follow along on twitter with the hashtag #LegalHack or at <a href=\"http://www.twitter.com/DCLegalHackers\">www.twitter.com/DCLegalHackers</a></p>", 
        "duration": 21600000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193491602/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193491602", 
        "maybe_rsvp_count": 0, 
        "name": "Citation Legal Hackathon", 
        "status": "upcoming", 
        "time": 1410616800000, 
        "updated": 1407252398000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "600 New Jersey Avenue NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 19547872, 
            "lat": 38.898173999999997, 
            "lon": -77.012237999999996, 
            "name": "Georgetown Law", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 11
    }, 
    {
        "created": 1404748848000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.\u00a0</p> <p>Join us on Tuesday, August 5, 2014 to legal hack crypto/ethereum law.</p> <p>7-7:30 Food, drinks and networking\u00a0\u00a0</p> <p>7:30-7:45 Introductions and Announcements\u00a0</p> <p>7:45 - 9:00 Presentations and Discussion</p> <p>Follow along on twitter with the hashtag #LegalHack or at www.twitter.com/DCLegalHackers</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193499412/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193499412", 
        "maybe_rsvp_count": 0, 
        "name": "#LegalHack Crypto / Ethereum Law", 
        "status": "upcoming", 
        "time": 1412204400000, 
        "updated": 1406226505000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "600 New Jersey Avenue NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 19547872, 
            "lat": 38.898173999999997, 
            "lon": -77.012237999999996, 
            "name": "Georgetown Law", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 5
    }, 
    {
        "created": 1404748918000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.\u00a0</p> <p>Join us on Tuesday, August 5, 2014 to legal hack standards organizations.</p> <p>7-7:30 Food, drinks and networking\u00a0</p> <p>7:30-7:45 Introductions and Announcements\u00a0</p> <p>7:45 - 9:00 Presentations and Discussion</p> <p>Follow along on twitter with the hashtag #LegalHack or at www.twitter.com/DCLegalHackers</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193499542/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193499542", 
        "maybe_rsvp_count": 0, 
        "name": "#LegalHack Standards Organizations", 
        "status": "upcoming", 
        "time": 1415232000000, 
        "updated": 1404749244000, 
        "utc_offset": -18000000, 
        "venue": {
            "address_1": "600 New Jersey Avenue NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 19547872, 
            "lat": 38.898173999999997, 
            "lon": -77.012237999999996, 
            "name": "Georgetown Law", 
            "repinned": false, 
            "state": "DC"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 5
    }, 
    {
        "created": 1404749084000, 
        "description": "<p>DC Legal Hackers is the DC Chapter of a growing movement of<a href=\"https://legalinformatics.wordpress.com/2013/09/12/legal-hacking-technology-and-innovation-groups/\">\u00a0more than twenty</a>\u00a0legal hacking, technology, or innovation groups around the country.\u00a0</p> <p>A legal hacker is someone who cares about the intersection of law and technology and seeks to improve legal practice through technology while simultaneously using legal skills to promote technological innovation and exploration.\u00a0</p> <p>Join us in December for our Legal Hackie Awards and Holiday Party</p> <p>7-7:30 Food, drinks and networking holiday party addition</p> <p>7:30-8:00 Award announcements and featured project recognition\u00a0</p> <p>8:00 - 9:00 Food, drinks and networking holiday party addition</p> <p>Follow along on twitter with the hashtag #LegalHack or at www.twitter.com/DCLegalHackers</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/DCLegalHackers/events/193499902/", 
        "group": {
            "group_lat": 38.919998168945312, 
            "group_lon": -77.040000915527344, 
            "id": 9201422, 
            "join_mode": "open", 
            "name": "DCLegalHackers", 
            "urlname": "DCLegalHackers", 
            "who": "Legal Hackers"
        }, 
        "headcount": 0, 
        "id": "193499902", 
        "maybe_rsvp_count": 0, 
        "name": "Legal Hackie Awards and Holiday Party (tentatively scheduled)", 
        "status": "upcoming", 
        "time": 1417651200000, 
        "updated": 1404749084000, 
        "utc_offset": -18000000, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 1
    }, 
    {
        "created": 1407614349000, 
        "description": "<p>For our August Meetup, we're thrilled to have <a href=\"http://ben.klemens.org/\">Dr. Ben Klemens</a> from the US Census Bureau talking about statistical models that tell stories. Rather than simply scaling up simple models, or throwing horsepower at black boxes, Ben prefers to estimate and test models whose structure reflects theories about the world and how people make decisions. In <a href=\"http://www.census.gov/srd/papers/pdf/rrs2014-06.pdf\">a recent article</a>, he developed a formal algebraic system of statistical models that makes it easier to define and fit complex models to data. And in a related <a href=\"http://apophenia.info/\">software package</a>, he can compare and combine models from genres including linear models, Bayesian hierarchies, and microsimulations. If you're interested in new ways to build useful, insightful, descriptive statistical models, you should definitely attend!</p> <p><b>Agenda:</b></p> <p>\u2022\u00a06:30pm -- Networking, Empenadas, and Refreshments</p> <p>\u2022\u00a07:00pm -- Introduction</p> <p>\u2022\u00a07:15pm -- Presentation and Discussion</p> <p>\u2022\u00a08:30pm -- Data Drinks (<i>Tonic,\u00a02036 G St NW</i>)</p> <p><b>Abstract:</b></p> <p>Social scientists develop nuanced, rich narratives. But when turning those narratives into testable models, a great deal is lost, leaving linear models or simple combinations of distributions. Can we do better? This talk will discuss the development of an algebraic system of models that provides a well-defined space of models, and transformations and combinations of models. This allows a researcher to develop descriptive models that mirror the narrative. Because even complex models have a standard form, they can be parameterized, estimated with data, and tested.</p> <p><br/><b>Bio:</b></p> <p>Ben Klemens has been doing statistical analysis and computationally intensive modeling of populations ever since getting his Ph.D. in Social Sciences from Caltech. He has written agent-based models and microsimulations for the Brookings Institution and the World Bank, and done statistical analyses with the National Institute of Mental Health and the US Census Bureau (where he currently works in the research division). He wrote a book on Modeling with Data, and was on the Kojo Nnamdi show. As a nonresident fellow at Brookings and with the Free Software Foundation, he has done work on ensuring that creative authors retain the right to use the software they write. Follow <a href=\"http://modelingwithdata.org/\">his blog</a> or his <a href=\"https://twitter.com/b__k\">Twitter account</a>.</p> <p><br/><b>Sponsors:</b></p> <p>This event is sponsored by the <a href=\"http://business.gwu.edu/decisionsciences/\">GWU Department of Decision Sciences</a>,\u00a0<a href=\"http://www.cloudera.com/\">Cloudera</a>,\u00a0<a href=\"http://bit.ly/12YljkP\">Statistics.com</a>,\u00a0<a href=\"https://corporate.livingsocial.com/browsealljobs/?deep_link=/jobs/olpfYfwH\">LivingSocial</a>,\u00a0<a href=\"https://www.ibm.com/ascdc\">IBM Analytics Solution Center</a>,\u00a0<a href=\"http://novetta.com/\">Novetta Solutions</a>,\u00a0<a href=\"http://datamininglab.com/\">Elder Research</a>, and\u00a0<a href=\"http://www.five9group.com/\">Five 9 Group</a>.</p>", 
        "duration": 7200000, 
        "event_url": "http://www.meetup.com/Data-Science-DC/events/199998422/", 
        "group": {
            "group_lat": 38.909999847412109, 
            "group_lon": -77.019996643066406, 
            "id": 2215331, 
            "join_mode": "open", 
            "name": "Data Science DC", 
            "urlname": "Data-Science-DC", 
            "who": "Data Scientists"
        }, 
        "headcount": 0, 
        "id": "199998422", 
        "maybe_rsvp_count": 0, 
        "name": "Transforming and Combining Statistical Models", 
        "rsvp_limit": 550, 
        "status": "upcoming", 
        "time": 1409265000000, 
        "updated": 1407680279000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "2201 G St. NW", 
            "city": "Washington", 
            "country": "us", 
            "id": 13300352, 
            "lat": 38.898952000000001, 
            "lon": -77.048942999999994, 
            "name": "GWU, Funger Hall, Room 108", 
            "repinned": false, 
            "state": "DC", 
            "zip": "20052"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 416
    }, 
    {
        "created": 1408548417000, 
        "description": "<p>For September, we'll be discussing three tech projects and their impact on local transportation issues.</p> <p>\u2022\u00a0Nick Ramfos of <a href=\"http://www.mwcog.org/\">MWCOG</a> will show us their new <a href=\"http://www.commuterconnections.org/\">Commuter Connections</a> app which helps you find carpool partners, locate park-and-ride lots, and access other tools to find easier, less expensive ways to get to work.</p> <p>\u2022\u00a0Stephanie Nguyen of <a href=\"http://silicalabs.com/\">Silica Labs</a> will preview their upcoming \"Landmark\" app, which helps people navigate streets using landmarks rather than traditional maps.</p> <p><br/>\u2022\u00a0Lou Huang will show us <a href=\"http://streetmix.net/\">streetmix</a>, a project he worked on as a <a href=\"http://www.codeforamerica.org/\">Code for America</a> fellow, and introduce us to a related Code for America project, <a href=\"http://www.transitmix.net/\">transitmix</a>.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/202085172/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "202085172", 
        "maybe_rsvp_count": 0, 
        "name": "Cool Mobility Apps: September Edition", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1409868000000, 
        "updated": 1408851293000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 45
    }, 
    {
        "created": 1408392086000, 
        "description": "<p>For October, we'll be discussing four tech projects and their impact on local transportation issues.</p> <p>\u2022\u00a0Trevor Gerhardt of <a href=\"http://conveyal.com/\">Conveyal</a> will show us their <a href=\"http://mobilitylab.org/transit-tech/\">Transit Tech Initiative</a> with Arlington County, specifically the \"evaluating a commute\" portion of the program.</p> <p>\u2022\u00a0Eric Meyer will tell us about the Baltimore-based <a href=\"http://www.haystackmobile.com/\">Haystack</a> mobile app, which lets people buy and sell street-side parking spaces.</p> <p>\u2022\u00a0Chase Donnelly and\u00a0Peter Mazzeo will demo their new <a href=\"http://boontrek.com/\">Boontrek</a> app, which\u00a0creates a community marketplace for ride sharing.</p> <p><br/>\u2022\u00a0Peter Shashkin and Vitaliy Fedonkin from <a href=\"http://www.eastbanctech.com/\">EastBanc Technologies</a> will show us TransitIQ, which analyzes transit data, detecting anomolies, bus bunching, and more. EastBanc works with SmarTrip cards and\u00a0is the company behind\u00a0<a href=\"http://developer.wmata.com/\">developer.wmata.com</a>.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/201709462/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "201709462", 
        "maybe_rsvp_count": 0, 
        "name": "Cool Mobility Apps: October Edition", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1412287200000, 
        "updated": 1408905160000, 
        "utc_offset": -14400000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 17
    }, 
    {
        "created": 1407622606000, 
        "description": "<p>We had a blast at our last Bike Hack Night in May, so we're doing it again in November. We're looking for folks who can demo cool bike-related apps or data visualizations. Or if you have a \u00a0cool data-generating bike gadget, that's good too.</p> <p>\u2022 Betsy\u00a0Emmons will show her animated\u00a0<a href=\"http://mapstory.org/maps/1736/\">MapStory</a>\u00a0on the history of bike lanes in DC.</p> <p><br/>\u2022\u00a0Lia Seremetis of <a href=\"http://dcbikeparty.com/\">DC Bike Party</a>\u00a0will talk about how we GPS-tracked a big bike ride and made an animation of it.</p> <p>\u2022\u00a0Reg Viray from the\u00a0<a href=\"https://www.vtti.vt.edu/\">Virginia Tech Transportation Institute</a>\u00a0will talk about bicycles and the future of connected vehicles.\u00a0</p> <p><br/>\u2022\u00a0<a href=\"http://tedullrich.com/\">Ted\u00a0Ullrich</a> of <a href=\"http://tomorrow-lab.com/\">Tomorrow Lab</a>\u00a0in New York City will show us the <a href=\"http://waycount.com/\">WayCount</a> device, which can be used to crowdsource bike traffic count data.</p> <p>We'll post additional speakers as they get scheduled. Other than CaBi, what other sorts of bike-related data is out there?\u00a0If you have a bike-related app or data visualization that's creative and local, we want to see it!</p> <p>Read about the last Bike Hack Night:\u00a0<a href=\"http://mobilitylab.org/2014/05/28/transportation-techies-show-what-can-be-done-with-bike-data/\">Transportation Techies Show What Can Be Done With Bike Data</a>.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/200015252/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "200015252", 
        "maybe_rsvp_count": 0, 
        "name": "Bike Hack Night II", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1415314800000, 
        "updated": 1409029140000, 
        "utc_offset": -18000000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 23
    }, 
    {
        "created": 1407908606000, 
        "description": "<p>Putting out the call for new and exciting apps and data visualizations about Capital Bikeshare. Read about <a href=\"http://mobilitylab.org/2013/12/11/capital-bikeshare-hackers-pedal-their-wares-at-mobility-lab/\">CaBiHackNight I</a> and <a href=\"http://mobilitylab.org/2014/08/11/cabi-hack-night-2-brings-out-nerds-who-love-bikesharing/\">CaBiHackNight II</a> to get an idea of how it works. This is a \"show and tell,\" not a hackathon. Got a cool CaBi project? We'd love to see it!</p> <p>We'll add speakers here as folks sign up:</p> <p>\u2022\u00a0Trevor Gerhardt will show us a <a href=\"http://trevorgerhardt.com/hexacabi/\">dcjs data explorer</a> for CaBi.</p> <p>\u2022\u00a0<a href=\"http://codemonkey.io/\">Mathias Hansen</a> will show us how he visualizes an individual's trip histories with his Trip statistics app.</p> <p>\u2022 Paul DeMaio, the program manager of Arlington's Capital Bikeshare service, will share a study on CaBi\u2019s first-mile/last-mile ridership.</p>", 
        "event_url": "http://www.meetup.com/Transportation-Techies/events/200661602/", 
        "group": {
            "group_lat": 38.889999389648438, 
            "group_lon": -77.069999694824219, 
            "id": 11092702, 
            "join_mode": "open", 
            "name": "Transportation Techies", 
            "urlname": "Transportation-Techies", 
            "who": "Techies"
        }, 
        "headcount": 0, 
        "id": "200661602", 
        "maybe_rsvp_count": 0, 
        "name": "CaBi Hack Night III", 
        "rsvp_limit": 60, 
        "status": "upcoming", 
        "time": 1417734000000, 
        "updated": 1408715147000, 
        "utc_offset": -18000000, 
        "venue": {
            "address_1": "1501 Wilson Blvd, Suite 1100", 
            "city": "Arlington", 
            "country": "us", 
            "id": 16609032, 
            "lat": 38.895149000000004, 
            "lon": -77.074043000000003, 
            "name": "Mobility Lab", 
            "repinned": false, 
            "state": "VA", 
            "zip": "22209"
        }, 
        "visibility": "public", 
        "waitlist_count": 0, 
        "yes_rsvp_count": 10
    }
])